### ISSUE TITLE
Move the DSDL package generator to Nunavut

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal/pycyphal#110]
https://github.com/UAVCAN/nunavut/issues/102

- Move the code generation templates from [`pyuavcan/dsdl/_templates`](https://github.com/UAVCAN/pyuavcan/tree/master/pyuavcan/dsdl/_templates)

- Move the support library (base classes, support functions, serialization logic) from [`pyuavcan/dsdl`](https://github.com/UAVCAN/pyuavcan/tree/master/pyuavcan/dsdl)

- Refactor the `pyuavcan.dsdl` module to be a thin wrapper over Nunavut.

- Move the verification suite from [`tests/dsdl`](https://github.com/UAVCAN/pyuavcan/tree/master/tests/dsdl)

The generated code will be dependent on NumPy.

**Comment by pavel-kirienko** [comment]
@coderkalyan @bbworld1 might either of you be interested in working on this?

**Comment by coderkalyan** [comment]
I can take a look, I think
