### ISSUE TITLE
Rename the library

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal/pycyphal#214]
Context: https://forum.uavcan.org/t/uavcan-v1-is-now-cyphal/1622/3

The most obvious options are PyOpenCyphal, PyCyphal, and Pyphal. Please do share suggestions if there are any.

**Comment by silverv** [comment]
PyCyphal

**Comment by pavel-kirienko** [comment]
@thirtytwobits are we okay with PyCyphal or Pyphal? (I personally prefer the latter)
