### ISSUE TITLE
Make Windows a supported platform for tests and development of Pycyphal

### ISSUE THREAD

**Issue by silverv** [OpenCyphal/pycyphal#263]

**Comment by silverv** [comment]
You said that it doesn't work on Windows and it seems to be true, CI is failing anyway so we can't say that CI works so Windows is a viable development platform for this.

**Comment by silverv** [comment]
https://ci.appveyor.com/project/Zubax/pycyphal/builds/45479327/job/lnj20bour4iou6y5

**Comment by pavel-kirienko** [comment]
Windows is supported as a target platform, and there is a CI workflow to verify this. The workflow is functional, although it occasionally fails because some tests are a bit flaky (which is a separate issue not related to Windows). There are no plans to support Windows as a development platform.
