### ISSUE TITLE
Support more python-can configuration options

### ISSUE THREAD

**Issue by chemicstry** [OpenCyphal/pycyphal#264]
Current [implementation](https://github.com/OpenCyphal/pycyphal/blob/master/pycyphal/transport/can/media/pythoncan/_pythoncan.py#L168) splits environment variable by colon and checks if there are excatctly 2 parts. This does not work with some of the python-can configuration options, like SLCAN over TCP where channel name is `socket://192.168.254.254:5000` instead of just `COM1`.

Would it make sense to split just the first colon and ignore the rest? Or would it be better to use some other format than colon?

**Comment by pavel-kirienko** [comment]
>Would it make sense to split just the first colon and ignore the rest?

Yes, a change request would be accepted.
