### ISSUE TITLE
Migrate to Nunavut v2

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal/pycyphal#277]

**Comment by Willmac16** [comment]
Is there a list of remaining tasks to move to Nunavut v2?

I would be happy to help if I can, as my build system would be greatly simplified without two different versions of Nunavut to wrangle.

**Comment by pavel-kirienko** [comment]
List of tasks to move to Nunavut v2:

Remove the DSDL templates completely and instead invoke the default Python generator available in Nunavut v2. These directories need to go: `pycyphal/dsdl/_templates`, `pycyphal/dsdl/_serialized_representation`. `_builtin_form.py`, `_composite_object.py` are not needed either because the respective functionality has been moved into the Nunavut-generated support module.

Upgrade `_compiler.py` to invoke the new Nunavut API correctly.

Remove all DSDL-related tests affected by the removal of the modules mentioned above. They have already been migrated to Nunavut.
