### ISSUE TITLE
Is very slow on Windows

### ISSUE THREAD

**Issue by silverv** [OpenCyphal/pycyphal#286]
Perhaps causes #281 and also affects Yukon usability on Windows devices.

**Comment by pavel-kirienko** [comment]
@silverv we should try increasing the resolution of the system timer as done in the PyCyphal test suite:

https://github.com/OpenCyphal/pycyphal/blob/029fdb5b5a158372103edf436298bc3559377dd8/tests/conftest.py#L63

More on this in the Windows API docs

**Comment by silverv** [comment]
It would probably make sense to go for a lower than 6 ms value, ideally a lower than millisecond value

**Comment by silverv** [comment]
I don't understand why setting the delay even even higher helped the tests

**Comment by pavel-kirienko** [comment]
Not sure what delay you are referring to. There are no delays here, the referenced API function changes the system timer resolution. It should be possible to go down to 1 ms, I would try that.
