### ISSUE TITLE
py.typed Typing

### ISSUE THREAD

**Issue by manforowicz** [OpenCyphal/pycyphal#342]
According to [PEP 561](https://peps.python.org/pep-0561/),
> Package maintainers who wish to support type checking of their code MUST add a marker file named py.typed to their package supporting typing.

I noticed that MyPy refuses to type-check pycyphal, and auto-generated DSDLs because they don't have a `py.typed` file.

Would it be a good idea to add a `py.typed` file to library code and auto-generated DSDLs?

**Comment by pavel-kirienko** [comment]
yes please
